
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0
    pool:
      min-idle: 0
      max-wait: -1
      max-idle: 8
      max-active: 8
server:
  port: 10001
  tomcat:
    max-connections: 1000
    max-threads: 200
    uri-encoding: UTF-8
  servlet:
    context-path: /moreds

#httpclient配置
http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
